### ISSUE TITLE
Add eslint-plugin as optional peer dependency (support Yarn PNP)

### ISSUE THREAD

**Issue by blutorange** [sweepline/eslint-plugin-unused-imports#36]
I was adding this plugin to a TypeScript project that uses [Yarn PNP in strict mode](https://yarnpkg.com/features/pnp) and noticed that it kept reporting arguments in function types as unused. After looking a bit into it, I realized that this plugin attempts to require `@typescript-eslint/eslint-plugin`, catches any errors and falls back to the standard ESLint `no-unused-vars` rule. When Yarn PNP strict mode is used, that require call (silently) fails because this package does not declare a dependency on `eslint-plugin`.

As a workaround I temporarily added a `packageExtensions` entry to the `.yarnrc.yml` and could confirm that this is indeed the issue.

```yaml
  "eslint-plugin-unused-imports@*":
    peerDependencies:
      "@typescript-eslint/eslint-plugin": "^4.14.2"
    peerDependenciesMeta:
      "@typescript-eslint/eslint-plugin":
        optional: true
``` 

So I think adding `eslint-plugin` as an optional peer dependency to the `package.json` of this package should fix the issue:

```json
{
  "peerDependencies": { 
    "@typescript-eslint/eslint-plugin": "^4.14.2"
  },
  "peerDependenciesMeta": {
    "@typescript-eslint/eslint-plugin": {
      "optional": true
    }
  }
}
```

Awesome plugin by the way, lets me completely disable the `fixImports` feature of VSCode in favor of a pure ESLint solution.
